[project]
name = "lab02-labs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "duckdb>=1.4.1",
    "ipykernel>=7.0.1",
    "psycopg[binary]>=3.2.10",
]
